# Site settings
title: Sergio Ibañez
description: 'Base de operaciones'
url: 'http://sergioibs.es'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sergio Ibañez'
  email: 'sergio12290@gmail.com'
  twitter_username: sergioibs
  facebook_username: sergioibs
  github_username:  sergioibs
  linkedin_username:  sergioibanezsanahuja

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
